북마크, 좋아요 뷰 추가
wecode-bootcamp-korea/14-1st-HOT-backend pull request #24
Opened 2020-11-24 09:31 UTC by gemma-Kim

>wecode PR message template 및 체크 리스트 입니다. 

## 수정 사항 간략한 한줄 요약
- 좋아요 뷰
- 북마크 뷰
		 
## 수정 사항들 자세한 내용
- product, post, collection 중에 어떤  id가 있냐에 따라 맞는 테이블에 로우 추가 및 제거
- 좋아요, 좋아요 취소 뷰. 만약 해당 유저가 post를 이미 좋아요 해서 테이블에 로우가 존재하는 경우 좋아요 거부

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-25 05:33 UTC, soheon-lee commented on user/views.py
> +                print('b')
사용하지 않는 test용 print 문은 제거해주세요

2020-11-25 05:33 UTC, soheon-lee commented on user/views.py
> +                    return JsonResponse({'messsage':'INVALID_BOOKMARK'}, status=400)
PostBookmark, ProductMookmar, CollectionBookmark 모두 적용되는 이야기인데, request에 들어있는 user에게서 이미 id를 바로 꺼내오실 수 있습니다. 따라서 request.user.id를 이용해 User 객체 instance를 query 해오신 다음에 또, 다시 그 객체의 id를 찾는 과정을 하시기 보다는 request.user.id를 바로 user_id로 사용하시어 필터링때도 쭉 사용하시면 좋습니다 :)
이유는, `User.objects.get`을 하는 쿼리문을 하나 줄일 수 있기 때문입니다 :)

2020-11-25 05:33 UTC, soheon-lee commented on user/views.py
> +
```python
if:
    return
elif:
    return
```
의 구조보다는
```python
if:
    return
if:
    return
```
구조가 좀 더 직관적이고 좋습니다 :)

2020-11-25 05:33 UTC, soheon-lee commented on user/views.py
> +             user = User.objects.get(id=request.user.id)
여기에서도 마찬가지로 user 객체 가져오시지 않으셔도 됩니다

2020-11-25 05:33 UTC, soheon-lee commented on user/views.py
> +             CollectionBookmark.objects.filter(user_id=user.id, collection_id=data['collection_id']).delete()
gooooood!!

2020-11-25 05:33 UTC, soheon-lee commented on user/views.py
>              return JsonResponse({'message':'KEY_ERROR'}, status=400)
여기에서도 마찬가지로 user 객체 가져오시지 않으셔도 됩니다

2020-11-25 05:39 UTC, gemma-Kim commented on user/views.py
> +                print('b')
넹

2020-11-25 05:45 UTC, gemma-Kim commented on user/views.py
> +                    return JsonResponse({'messsage':'INVALID_BOOKMARK'}, status=400)
수정하겠습니다 :)

2020-11-25 05:47 UTC, gemma-Kim commented on user/views.py
> +
잘 알았습니당 감사합니당

2020-11-25 05:47 UTC, gemma-Kim commented on user/views.py
> +             user = User.objects.get(id=request.user.id)
수정했습니당

2020-11-25 05:48 UTC, gemma-Kim commented on user/views.py
> +             CollectionBookmark.objects.filter(user_id=user.id, collection_id=data['collection_id']).delete()
아리가또고쟈이마스 😇

2020-11-25 05:49 UTC, gemma-Kim commented on user/views.py
>              return JsonResponse({'message':'KEY_ERROR'}, status=400)
like를 사용하지 않을거라 당장은 괜찮은데 delete method를 사용해도 될까요? 팔로우, 언팔로우에서 따로 post로 만들라고 리뷰 받았어서요!

2020-11-26 07:49 UTC, jamessoun93 requested changes

2020-11-26 07:49 UTC, jamessoun93 commented on user/'
> +import re, json, bcrypt, jwt
이 파일의 정체는!?

2020-11-26 07:49 UTC, jamessoun93 commented
conflict 발생했네요 수정해서 올려주세요

2020-11-26 10:33 UTC, closed without merging